### ISSUE TITLE
database-disk-image-malformed

### ISSUE THREAD

**Issue by unangwarsodi** [siara-cc/esp32_arduino_sqlite3_lib#8]
can one database have many tables?, I try one database of two tables and it doesn't work and raises a "database-disk-image-malformed" error message in the second table

**Comment by siara-cc** [comment]
One database can have many tables.  I may be that your sd card is getting corrupted often presumably because of power fluctuations.   I suggest you to try storing the database on the internal SPIFFS.  It could have more tolerance to such issues.

Also, please note these storage media (sdcard or spiffs) are not like hard disk or RAM.  They have limitation on how many writes can be made to each sector.  Usually after more than 10000 writes to one sector it gives such problems.  So to avoid such problems, need to ensure that same area is not written very often.

**Comment by siara-cc** [comment]
https://github.com/siara-cc/esp32_arduino_sqlite3_lib#limitations-of-flash-memory

**Comment by unangwarsodi** [comment]
can you give an example of the script?
Thanks

**Comment by siara-cc** [comment]
For using SPIFFS, there is already an example in the repo.

**Comment by unangwarsodi** [comment]
how to reopen connection database after close?
